[package]
name = "dohres"
version = "0.1.0"
authors = ["Ivan Nejgebauer <inejge@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
trust-dns = { version = "0.15.0", features = ["dns-over-https-rustls"] }
failure = "0.1.3"
rustls = "0.14.0"
libc = "0.2.44"
